
name: HTML Validation and Deployment

on:
  push:
    branches:
      - main

jobs:
  validate-html:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate HTML using htmlhint
        run: |
          npm install -g htmlhint
          htmlhint ITBIN-2211-0257/student_registration.html

  deploy:
    name: Deploy to GitHub Pages
    needs: validate-html
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ITBIN-2211-0257/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
